### ISSUE TITLE
Did you test coco MAP?

### ISSUE THREAD

**Issue by zerollzeng** [michalfaber/tensorflow_Realtime_Multi-Person_Pose_Estimation#4]
Thanks for you great job!
did you test map on coco dataset, I run your pretrained mobilenetv2 model on some sample iamges , and the result seems not very accurate. eg
![image](https://user-images.githubusercontent.com/38289304/71608733-43d47880-2bbe-11ea-9d32-a10f5267640e.png)

**Comment by michalfaber** [comment]
Despite quite good performance, heat maps based solution is not very accurate. This is because output heat maps have lower resolution than input image due to the downsampling steps in a deep neural network (x8) For input image of size 224x224, heat map resolution is only 28x28. This causes quantization errors.

**Comment by lengyuner** [comment]
Where do you find the pretrained mobilenetv2 model?
